### PR TITLE
A crude attempt at publishing .proto files

### PR DESCRIPTION
**Pull request by ogolberg**
Package up and publish the original .proto files and .proto files stripped of custom kotlin-only options as standalone artifacts. This enables other systems that  don't care about the Kotlin domain code (e.g. archiving and analytics) to consume the proto schema _without unpacking kotlinExtensions.proto_.

### CODE REVIEW

**Comment by aparmet-toast** [comment]
What goes wrong if they try to use the files with Kotlin-only options?

**Comment by ogolberg** [comment]
Nothing, as long as they make "kotlinExtensions.proto" available to the protoc compiler. Gradle protobuf plugin does that automatically by unpacking all .proto files packaged into dependency jars.

**Comment by aparmet-toast** [comment]
So they wouldn't be compatible from, say, the JS protobuf compiler - it would fail to generate?

**Comment by ogolberg** [comment]
> So they wouldn't be compatible from, say, the JS protobuf compiler - it would fail to generate?

They are compatible with any protobuf generator as long as kotlinExtensions.proto is available on the include path (even though they don't understand the kotlin options, they will fail on broken imports).

So for example, let's say you're building a node app that needs this .proto schema. And your build tooling is not gradle but rather npm + gulp or something like that. You would have to write a gulp script that fetches the pb-and-k jar from artifactory, and unzips kotlinExtensions.proto from it it next to the .proto schema. That's just an extra step.

**Comment by aparmet-toast** [comment]
That's what I understood.

**Pull request merged**
